### PR TITLE
Add Embroider support

### PR DESCRIPTION
**Pull request by ctjhoa**

### CODE REVIEW

**Comment by ctjhoa** [comment]
Ok I need to rewrite my commits because my npm version is different and the package-lock is fucked up.

**Comment by amk221** [comment]
Interesting, thanks for this! We've not had chance to play with Embroider yet.

**Comment by ctjhoa** [comment]
@amk221 Should be good now

**Comment by amk221** [comment]
Thanks, I'm up to speed now.

All passes locally, but not on Travis.

I don't suppose you can make sense of this output: https://travis-ci.org/github/zestia/ember-select-box/jobs/765467368

**Comment by ctjhoa** [comment]
@amk221 I'm able to reproduce the issue with the `CI` env variable
```
CI=true node_modules/.bin/ember try:one embroider-safe
```

**Comment by ctjhoa** [comment]
It seems to be a Embroider / qunit bug, you can disable those 2 scenario for the moment if you want.

**Comment by amk221** [comment]
Thanks, seeking more help in discord. I can get a release out now though, cheers

**Pull request merged**
