### PR TITLE
ci: bump node version to v16 to prevent unresolved deps

### PR DESCRIPTION
**Pull request by derrabauke**
The addon is missing the [eslint-config-standard peerDep](https://github.com/zestia/eslint-config/blob/4cd68463157aa4f90143111bfd3523fee37b1580/package.json#L37) to properly run the linting job.

### CODE REVIEW

**Comment by amk221** [comment]
It's [here](https://github.com/zestia/eslint-config/blob/main/package.json#L37), but doesn't seem to be working

**Comment by derrabauke** [comment]
Alright, got it! :boom: 

CI says: 
```
Environment details
  node: v14.21.3
  npm: 6.14.18
```

`npm` prior [version 7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/) will not automatically install peerDependencies.

For npm `v4-v6` the following is true :
> When a dependency is listed in a package as a peerDependency, it is not automatically installed. Instead, the code that includes the package must include it as its dependency.[^1]

Upgrading the `node` version to `16` in the CI should resolve it.

---
[^1]:(https://flaviocopes.com/npm-peer-dependencies/)

**Comment by derrabauke** [comment]
Btw: `node v14` has reached end of life anyways. One should consider bumping to `18` :thinking:

**Comment by amk221** [comment]
thanks for the nudge, running ember-cli-update seems to have mostly solved it.

**Comment by derrabauke** [comment]
> thanks for the nudge, running ember-cli-update seems to have mostly solved it.

Nice! *Keep it moving!*

**Pull request closed without merging**
